### ISSUE TITLE
Use the WebKitGTK 4.1 API builds when available

### ISSUE THREAD

**Issue by bertogg** [bibledit/debian#1]
WebKitGTK switched to soup3 a while ago while keeping the older soup2 build for compatibility.

For apps that don't use libsoup directly (and therefore don't need to port the code to the new soup API) the only change that's needed is using webkit2gtk-4.1 instead of webkit2gtk-4.0.

I didn't find the repository with the source code, but in this case this should be enough:

```
--- a/configure.ac
+++ b/configure.ac
@@ -61,8 +61,10 @@ PKG_CHECK_MODULES(GTK, gtk+-3.0,,AC_MSG_ERROR(Gtk3 development version is needed
 AC_SUBST(GTK_LIBS)
 AC_SUBST(GTK_CFLAGS)
 
-PKG_CHECK_MODULES([WEBKIT2GTK], [webkit2gtk-4.0],, [
-  PKG_CHECK_MODULES([WEBKIT2GTK], [webkit2gtk-3.0],,AC_MSG_ERROR(Webkit2Gtk development version is needed.))
+PKG_CHECK_MODULES([WEBKIT2GTK], [webkit2gtk-4.1],, [
+  PKG_CHECK_MODULES([WEBKIT2GTK], [webkit2gtk-4.0],, [
+    PKG_CHECK_MODULES([WEBKIT2GTK], [webkit2gtk-3.0],,AC_MSG_ERROR(Webkit2Gtk development version is needed.))
+  ])
 ])
 AC_SUBST(WEBKIT2GTK_LIBS)
 AC_SUBST(WEBKIT2GTK_CFLAGS)
```

**Comment by teusbenschop** [comment]
Thank you for the patch to then use the newer version of the webkit2gtk-4. The source code for the Debian build, and other Linux builds is generated through a script. The original configure.ac is here: https://github.com/bibledit/cloud/blob/master/configure.ac. Then the scripts to create the Linux source are here: https://github.com/bibledit/linux. What I'll do is to apply your patch and test it. Thanks for the contribution.

**Comment by bertogg** [comment]
Ah, the cloud repository, I see it now, thanks!

**Comment by teusbenschop** [comment]
In Debian Sid there is package ```libwebkit2gtk-5.0-0```. 

Is it a good idea to update the file ```configure.ac``` to allow for version Webkit2 version 5.0 too?

**Comment by bertogg** [comment]
> In Debian Sid there is package `libwebkit2gtk-5.0-0`.

Please don't use that one, that's unstable and is going to disappear soon, hopefully before the Debian 12 "bookworm" release.

**Comment by teusbenschop** [comment]
The patch made it in the configure.ac, see https://github.com/bibledit/cloud/blob/master/configure.ac. Thank you for this.
